export const MINIFIED_SIDEBAR_WIDTH_PX = 60;
export const MINIFIED_SIDEBAR_WIDTH_CSS =`${MINIFIED_SIDEBAR_WIDTH_PX}px`;

export const OPENED_SIDEBAR_WIDTH_PX = 240;
export const OPENED_SIDEBAR_WIDTH_CSS =`${OPENED_SIDEBAR_WIDTH_PX}px`;

export const MOBILE_VIEW_HEIGHT_PX = 60;
export const MOBILE_VIEW_HEIGHT_CSS = `${MOBILE_VIEW_HEIGHT_PX}px`;

export const MOBILE_BREAKPOINT_PX = 1280;